<?php

// $Id: mm_auto_run.module,v 1.1.2.5 2010/02/23 05:18:01 arthuregg Exp $


/**
 * @file
 * Provides automatic running for specific configurations from media mover
 */


/* ********************************************** */
/* DRUPAL HOOKS                                   */
/* ********************************************** */


/**
 * Implements hook_menu().
 *
 * @return array
 */
function mm_auto_run_menu() {
  $items = array();
  $items['admin/build/media_mover/settings/mm_auto_run'] = array(
    'title' => 'Auto Run',
    '#description' => t('Specify Media Mover configurations to automatically run.'),
    'access arguments' => array('administer media_mover'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mm_auto_run_settings_form'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}


/**
 * Implements hook_nodeapi().
 *
 * @param object $node
 * @param string $op
 * @param string $a3
 * @param string $a4
 */
function mm_auto_run_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  // We only run on update or insert
  if ($op == 'insert' || $op == 'update') {
    // Get the list of configurations
    $configurations = variable_get('mm_auto_run_configs', FALSE);
    if ($configurations) {
      // Prepare to store what configurations have been run
      $has_run = array();
      // Run each configuration that is enabled
      foreach ($configurations as $cid => $enabled) {
        if ($enabled && ! in_array($cid, $has_run)) {
          $config = media_mover_api_get_configuration($cid);
          $has_run[$cid] = TRUE;
          // run the media mover configuration on this node
          media_mover_api_run_config($config, TRUE, $node->nid);
        }
      }
    }
  }
}


/* ********************************************** */
/* INTERNAL FUNCTIONS                             */
/* ********************************************** */


/**
 * Builds the settings form, used on admin/settings/mm_auto_run and
 * admin/media_mover/settings
 *
 * @return array
 */
function mm_auto_run_settings_form() {
  // build some description information
  $form['auto_run'] = array(
    '#type' => 'fieldset',
    '#title' => t('Media Mover Auto Run'),
    '#description' => t('Select which Media Mover configurations you would like to run automatically when a user creates or updates a node.
      This will only work with configurations that harvest their data from nodes.
      Note that by default, any enabled Media Mover configuration will be run each time Cron runs.'),
    '#collapsible' => TRUE,
  );

  // get a list of all current MM configurations
  $configurations = media_mover_api_configurations_get();
  foreach ($configurations as $configuration) {
    $options[$configuration->cid] = '<strong>'. l($configuration->name, 'admin/build/media_mover/configurations/' . $configuration->cid) .'</strong>'. $configuration->description;
  }

  $form['auto_run']['mm_auto_run_configs'] = array(
    '#title' => t('Select the configurations to run'),
    '#type' => 'checkboxes',
    '#options' => $options,
    '#default_value' => variable_get('mm_auto_run_configs', array()),
  );

  return system_settings_form($form);
}