<?php

// $Id: mm_control.module,v 1.1.2.4 2010/04/20 06:12:51 arthuregg Exp $

/**
 * @file
 * This module provides mechanisms to limit
 * when media mover configurations are run and
 * reporting on various items
 */


/* ****************************************** */
/* Drupal Hook Functions                      */
/* ****************************************** */


/**
 * Implements hook_menu().
 *
 * @return array
 */
function mm_control_menu() {
  $items = array();
  $items['admin/build/media_mover/settings/control'] = array(
    'title' => 'Control services',
    'description' => t('Configure control services.'),
    'access arguments' => array('administer media_mover'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mm_control_admin_form'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}


/**
 * Implements hook_cron().
 */
function mm_control_cron() {
  // Monitor for stuck files
  mm_control_monitor_files();
}


/**
 * Implements hook_mail().
 *
 * @param unknown_type $key
 * @param unknown_type $message
 * @param unknown_type $params
 * @return unknown_type
 */
function mm_control_mail($key, &$message, $params) {
  $language = $message['language'];
  switch($key) {
    default:
      $message['subject'] = t($params['subject'], $params['params'], $language->language);
      $message['body'][] = t($params['body'], $params['params'], $language->language);
    break;
  }
}


/**
 * Implements hook_form_alter().
 */
function mm_control_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'media_mover_ui_add_config_form' || $form_id == 'media_mover_ui_config_edit_form') {
    mm_control_configuration_form($form);
  }
}


/**
 * Implements hook_nodeapi().
 *
 * @ingroup drupal_hooks
 */
function mm_control_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  // We only run on update or insert
  if ($op == 'insert' || $op == 'update') {
    // Get the configurations that need to be done
    if ($to_run = variable_get('mm_control_congfiguration_options', FALSE)) {
      foreach ($to_run['mm_control_node_run'] as $cid) {
        $has_run = array();
        // Run each configuration only once. Note that if new nodes
        // are created by a configuration, infinite loops can be created
        if ($enabled && ! in_array($cid, $has_run)) {
          $has_run[$cid] = TRUE;
          // run the media mover configuration on this node
          $configuration = media_mover_api_configuration_get($cid);
          // Run the harvest op
          $function = $configuration->steps[0]->callback;
          // Did we get any files?
          if ($files = $function($node)) {
            $configuration->run($file);
          }
          $configuration->run_nid($node->nid);
        }
      }
    }
  }
}


/* ****************************************** */
/* Form Functions                             */
/* ****************************************** */


/**
 * Provides the settigns form
 * @return $form
 */
function mm_control_admin_form() {
  $form = array();

  $form['text'] = array(
    '#type' => 'markup',
    '#value' => '<p>' . t('Control options provide you with the oppertunity to
      configure how and when Media Mover configurations are run. When options are
      enabled here, the configuration form will be displayed on the configuration
      add and edit forms. Each configuration can have it\'s own settings.'),
  );

  $enabled = variable_get('mm_control_monitors', array());
  $form['mm_control_cpu'] = array(
    '#title' => t('CPU'),
    '#type' => 'checkbox',
    '#default_value' => $enabled['cpu'],
    '#description' => t('Limit Media Mover configurations when CPU level is high.'),
  );
  $form['mm_control_file_time'] = array(
    '#title' => t('File monitor'),
    '#type' => 'checkbox',
    '#default_value' => $enabled['cpu'],
    '#description' => t('File duration monitor will email an administrator when a file has
      been in a action for a set amount of time.'),
  );
  $form['mm_control_file_count'] = array(
    '#title' => t('File count'),
    '#type' => 'checkbox',
    '#default_value' => $enabled['file_count'],
    '#description' => t('Limit how many files are operated on when a configuration runs'),
  );
  $form['mm_control_node_run'] = array(
    '#title' => t('Node create/update'),
    '#type' => 'checkbox',
    '#default_value' => $enabled['node_run'],
    '#description' => t('Run configurations when nodes are created and updated.'),
  );
  $form['mm_control_cron'] = array(
    '#title' => t('Cron'),
    '#type' => 'checkbox',
    '#default_value' => isset($enabled['cron']) ? $enabled['cron'] : TRUE,
    '#description' => t('Enable or disable configurations to run on cron.'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save')
  );
  return $form;
}


/**
 * Saves the control data
 *
 * @param $form
 * @param $form_state
 * @return unknown_type
 */
function mm_control_admin_form_submit($form, $form_state) {
  $options = array();
  foreach ($form_state['values'] as $key => $value) {
    if (strpos($key, 'mm_control') !== FALSE && $value) {
      $key = str_replace('mm_control_', '', $key);
      $options[$key] = TRUE;
    }
  }
  variable_set('mm_control_monitors', $options);
}


/**
 * Updates the media mover configuration add/edit form
 * @param unknown_type $form
 * @return unknown_type
 */
function mm_control_configuration_form(&$form) {
  if ($enabled = variable_get('mm_control_monitors', FALSE)) {

    // Add our submit handler so that control data can be saved
    $form['#submit'][] = 'mm_control_configuration_options_submit';

    $form['mm_control'] = array(
      '#type' => 'fieldset',
      '#title' => t('Run time control'),
    );

    // File duration monitor
    if ($enabled['file_time']) {
      $form['mm_control']['email_monitor'] = array(
        '#type' => 'fieldset',
        '#title' => t('Email monitoring'),
        '#collapsible' => TRUE,
        '#collapsed' => $configuration->settings->mm_control_email_file ? false : true,
        '#description' => t('Sometimes a files fail to complete during processing.
          If a file is running longer than the specified time, an email will be sent'),
      );
      $form['mm_control']['email_monitor']['mm_control_email_file'] = array(
        '#type' => 'checkbox',
        '#title' => t('Notify admin when a MM file has run to long'),
        '#default_value' => $configuration->settings->mm_control_email_file,
      );
      $form['mm_control']['email_monitor']['mm_control_email_file_email'] = array(
        '#type' => 'textfield',
        '#title' => t('Email address to notify'),
        '#default_value' => $configuration->settings->mm_control_email_file_email,
        '#description' => t('Email address to notify that a MM job has taken more than the set time.'),
      );
      $form['mm_control']['email_monitor']['mm_control_email_file_time'] = array(
        '#type' => 'textfield',
        '#title' => t('Monitor time'),
        '#default_value' => $configuration->settings->mm_control_email_file_time,
        '#description' => t('Minimum file running time before a notification is sent. Enter time in minutes'),
        '#size' => 4,
      );
    }

    // CPU threshold monitor
    if ($enabled['cpu']) {
      $form['mm_control']['cpu_monitor'] = array(
        '#type' => 'fieldset',
        '#title' => t('CPU monitoring'),
        '#collapsible' => TRUE,
        '#collapsed' => $configuration->settings->mm_control_cpu ? false : true,
        '#description' => t('Prevent the configuration from running when CPU load level is high.'),
      );
      $form['mm_control']['cpu_monitor']['mm_control_cpu'] = array(
        '#type' => 'checkbox',
        '#title' => t('Check CPU load before running.'),
        '#default_value' => $configuration->settings->mm_control_cpu,
      );
      $options = drupal_map_assoc(array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10));
      $form['mm_control']['cpu_monitor']['mm_control_cpu_threshold'] = array(
        '#title' => t('CPU threshold'),
        '#type' => 'select',
        '#options' => $options,
        '#default_value' => variable_get('mm_control_cpu_threshold', 4),
        '#description' => t('Set the CPU load where this configuration should no longer be run.'),
      );
      $options = array(1 => t('1 minute'), 2 => t('5 minute'), 3 => t('15 minute'));
      $form['mm_control']['cpu_monitor']['mm_control_cpu_average'] = array(
        '#title' => t('CPU sample'),
        '#type' => 'select',
        '#options' => $options,
        '#default_value' => variable_get('mm_control_cpu_average', 2),
        '#description' => t('Select the 1, 5, or 15 minute CPU load average to use as the threshold.'),
      );
    }

    // File count control
    if ($enabled['file_count']) {
      $form['mm_control']['file_count_enabled'] = array(
        '#type' => 'fieldset',
        '#title' => t('File count'),
        '#collapsible' => TRUE,
        '#collapsed' =>  $configuration->settings->mm_control_file_count ? FALSE : TRUE,
      );

      $form['mm_control']['file_count_enabled']['mm_control_file_count'] = array(
        '#type' => 'textfield',
        '#title' => t('Files at a time'),
        '#default_value' => isset($configuration->settings->mm_control_file_count) ? $configuration->settings->mm_control_file_count : 0,
        '#description' => t('Set the number of files to process at one time. Use
          smaller numbers to reduce load on servers and make it easier for multiple
          machines to work together. <em>0 is no limit per run</em>.'),
        '#size' => 4,
      );
    }

    // Run on node create/update
    if ($enabled['node_run']) {
      $form['mm_control']['node_run_enabled'] = array(
        '#type' => 'fieldset',
        '#title' => t('Node create/update'),
        '#collapsible' => TRUE,
        '#collapsed' =>  $configuration->settings->mm_control_node_run ? FALSE : TRUE,
      );

      $form['mm_control']['node_run_enabled']['mm_control_node_run'] = array(
        '#type' => 'checkbox',
        '#title' => t('Node create/update'),
        '#default_value' => $configuration->settings->mm_control_node_run,
        '#description' => t('When nodes are created or updated run this configuration.
          This is only usefull for configurations that harvest files from nodes'),
      );
    }

    // Run on cron
    if ($enabled['cron']) {
      $form['mm_control']['cron_settings'] = array(
        '#type' => 'fieldset',
        '#title' => t('Cron'),
        '#collapsible' => TRUE,
        '#collapsed' =>  $configuration->settings->mm_cron ? FALSE : TRUE,
      );

      $form['mm_control']['cron_settings']['mm_control_cron'] = array(
        '#type' => 'checkbox',
        '#title' => t('Node create/update'),
        '#default_value' => isset($configuration->settings->mm_control_cron) ? $configuration->settings->mm_control_cron : TRUE,
        '#description' => t('Enable or disable this configuration to run when Drupal\'s cron runs.'),
      );
    }
  }
}



/**
 * Tracks control options per configuration.
 *
 * We save an addtional copy of the the configuration data
 * here so that running from non-media mover functions is easier
 *
 * @param unknown_type $form
 * @param unknown_type $form_state
 * @return unknown_type
 */
function mm_control_configuration_options_submit($form, &$form_state) {
  $enabled = variable_get('mm_control_congfiguration_options', array());

  if (! isset($enabled['mm_control_file'])) {
    $enabled['mm_control_file'] = array();
  }
  if (! isset($enabled['mm_control_node_run'])) {
    $enabled['mm_control_node_run'] = array();
  }

  if ($cid = $form_state['storage']['configuration']->cid) {

    // Check for email status
    if ($form_state['values']['mm_control_file']) {
      $enabled['mm_control_file'][$cid] = array('file_email' => array(
          'email' => $form_state['values']['mm_control_file_email'],
          'time' => $form_state['values']['mm_control_file_time'],
          'last_sent' => 0
        ),
      );
    }
    else {
      unset($enabled['mm_control_file'][$cid]);
    }

    // Handle the run on node create/update
    if ($form_state['values']['mm_control_node_run']) {
      $enabled['mm_control_node_run'][$cid] = TRUE;
    }
    else {
      unset($enabled['mm_control_node_run'][$cid]);
    }

    // Cron settings
    if ($form_state['values']['mm_control_node_run']) {
      $enabled['mm_control_cron'][$cid] = TRUE;
    }
    else {
      unset($enabled['mm_control_cron'][$cid]);
    }

  }
  variable_set('mm_control_congfiguration_options', $enabled);
}


/* ****************************************** */
/* Monitor Functions                          */
/* ****************************************** */


/**
 * Checks for files that have run too long
 * @TODO
 */
function mm_control_monitor_files() {
  $enabled = variable_get('mm_control_congfiguration_options', array());
  foreach ($enabled['mm_control_file'] as $cid => $data) {
    $rows = array();
    $time = time() - ($settings['time'] * 60);
    $results = db_query("SELECT mmfid, cid, lock_date FROM {media_mover_files} WHERE lock_date < %d AND status = '%s' AND cid = '%s' ORDER BY lock_date", $time, MMA_FILE_STATUS_LOCKED, $cid);
    while ($result = db_fetch_array($results)) {
      $rows[] = t('%mmfid | %date | <%link>', array(
        '%mmfid' => $result['mmfid'],
        '%date' => format_date($result['lock_date']),
        '%link' => l($result['mmfid'], '/admin/build/media_mover/file/edit/' . $result['mmfid'], array('absolute' => TRUE))
      ));
    }

    $message = 'Media Mover\'s file monitor found files running longer than normal.
      You may want to consider decreasing your cron.php frequency or increase your PHP timeout,
      or examine the following configurations to see if there is a particular issue with them.';
    $mesage .= "\n\n" . implode("\n", $rows);

    $params = array(
      '%name' => $configuration->name,
      '%time' => intval( (time() - $configuration->start_time) / 60),
      '%site_name' => variable_get('site_name', '')
    );

    $email_params = array(
      'subject' => '[%sitename] Media Mover Monitor: long running files',
      'body' => $message,
      'params' => $params
    );

    // Only send one email per email frequency per configuration
    if ($settings['last_sent'] < (time() - variable_get('mm_control_email_frequency', 3600))) {
      $enabled[$cid]['last_sent'] = time();
      variable_set('mm_control_file_configurations', $enabled);
      drupal_mail('mm_control', 'long_running_files', $settings['email'], language_default(), $email_params);

    }
  }
}


/**
 * Get the current CPU load
 *
 * @param $time
 *   Int, 1,5,15 averages
 * @return $load
 *   Float, load value
 */
function mm_control_cpu_load($time = NULL) {
  if (! $time) {
    $time = variable_get('mma_cpu_limit_sample', 5);
  }
  ob_start();
    passthru('w' ." 2>&1", $command_return);
    $command_output = ob_get_contents();
  ob_end_clean();

  // split the output
  $pattern = "/.*load averages: ([0-9\.]*) ([0-9\.]*) ([0-9\.]*)/";
  preg_match($pattern, $command_output, $matches);
  return $matches[$time];
}


/* ****************************************** */
/* Media Mover Functions                      */
/* ****************************************** */


/**
 * Implements hook_media_mover_run_control().
 *
 * @param $step
 *   Object, Media Mover step object
 * @return
 *   Boolean, TRUE if the step can run, FALSE if not
 */
function mm_control_media_mover_run_control($step) {
  static $control_files = array();

  if ($enabled = variable_get('mm_control_monitors', FALSE)) {

    // CPU limiting
    if ($enabled['cpu']) {
      $configuration = media_mover_api_configuration_get($step->cid);
      if ($configuration->settigns->mm_control_cpu) {
        $load = mm_control_cpu_load($configuration->settings->mm_control_cpu_average);
        // Is the CPU load higher than the threshold?
        if ($load >= $configuration->settings->mm_control_cpu_threshold) {
          return FALSE;
        }
      }
    }

    // File number limit
    if ($enabled['file_count']) {
      $configuration = media_mover_api_configuration_get($step->cid);
      if ($configuration->settigns->mm_control_file_count) {
        // If this step hasn't been run before, initialize it
        if (! $control_files[$step->sid]) {
          $control_files[$step->sid]['file_count'] == 0;
        }
        // Have we reached the limit yet?
        if ($control_files[$step->sid]['file_count'] <= $configuration->settigns->mm_control_file_count) {
          $control_files[$step->sid]['file_count']++;
        }
        else {
          return FALSE;
        }
      }
    }

    // Cron limiting
    if ($enabled['cron']) {
      $configuration = media_mover_api_configuration_get($step->cid);
      if (! $configuration->settigns->mm_control_cron) {
        // Check to see if cron is currently running. We can only do this by
        // looking up the function call stack to make this thread safe
        $backtrace = debug_backtrace();
        // We are looking for the drupal_cron_run function
        foreach ($backtrace as $function_call) {
          if ($function_call['function'] == 'drupal_cron_run') {
            return FALSE;
          }
        }
      }
    }

  }

	return TRUE;
}